[package]
name = "mvcore"
version = "0.1.0"
edition = "2021"
description = "The MV core library. Rendering, assets and GUI."
authors = [
    "Maxim Savenkov <mqxf@mvteam.dev>",
    "Julian Hohenhausen <v22@mvteam.dev>"
]
readme = "README.md"
keywords = [
    "mvcore",
    "rendering",
    "wgpu",
    "assets",
    "gui"
]
categories = [
    "rendering",
    "rendering::engine",
    "gui",
    "graphics"
]
license-file = "LICENCE"

[[test]]
name = "test"
path = "tests/main.rs"
harness = false

[profile.release]
opt-level = 3
strip = true
lto = true
debug = false
panic = "unwind"

[features]
gui = ["dep:roxmltree"]
3d = ["dep:gltf"]
vr = ["dep:openxr", "dep:ash", "3d"]

[dependencies]
mvcore-proc-macro = { path = "Proc" }
mvutils = "0.3.5"
mvsync = "1.1.0"
include_dir = "0.7.3"
regex = "1.10.2"
glam = "0.25.0"
bytebuffer = "2.2.0"
json = "0.12.4"
image = "0.24.7"
bitflags = "2.4.1"
openal = "0.2.2"
itertools = "0.12.0"
# Do not update due to change in input (VirtualKeyCode -> Key(KeyCode || char)), this breaks our input system
winit = "0.28.4"
wgpu = { version = "0.18.0", features = ["spirv"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
log = "0.4.20"
env_logger = "0.10.1"
roxmltree = { version = "0.19.0", optional = true }
gltf = { version = "1.4.0", optional = true }
shaderc = "0.8.3"
num-traits = "0.2.17"
openxr = { version = "0.17.1", optional = true }
ash = { version = "0.37.3", optional = true }
