[package]
name = "mvcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mvutils = { path = "../MVUtils"}
priority-queue = "1.3.1"
include_dir = "0.7.3"
