[package]
name = "mvcore"
version = "0.1.0"
edition = "2021"
description = "The MV core library. Rendering, assets and GUI."
authors = [
    "Maxim Savenkov <mqxf@mvteam.dev>",
    "Julian Hohenhausen <v22@mvteam.dev>"
]
readme = "README.md"
keywords = [
    "mvcore",
    "rendering",
    "opengl",
    "vulkan",
    "assets",
    "gui"
]
categories = [
    "rendering",
    "rendering::engine",
    "gui",
    "graphics"
]
license-file = "LICENCE"

[[test]]
name = "test"
path = "tests/main.rs"
harness = false

[features]
vulkan = []
gui = ["dep:roxmltree"]
3d = ["dep:gltf"]

[dependencies]
mvutils = { path = "../MVUtils" }
include_dir = "0.7.3"
regex = "1.7.3"
glam = "0.24.0"
once_cell = "1.17.1"
bytebuffer = "2.1.1"
json = "0.12.4"
image = "0.24.6"
bitflags = "2.2.1"
openal = "0.2.2"
itertools = "0.10.5"
tokio = { version = "1.28.0", features = ["rt", "rt-multi-thread", "macros"] }
roxmltree = { version = "0.18.0", optional = true }
gltf = { version = "1.1.0", optional = true }
winit = "0.28.4"
wgpu = { version = "0.16.0", features = ["spirv"] }
glsl-to-spirv = "0.1.7"
bytemuck = { version = "1.13.1", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"
