[package]
name = "mvcore"
version = "0.1.0"
edition = "2021"
description = "The MV core library. Rendering, assets and GUI."
authors = [
    "Maxim Savenkov <mqxf@mvteam.dev>",
    "Julian Hohenhausen <v22@mvteam.dev>"
]
readme = "README.md"
keywords = [
    "mvcore",
    "rendering",
    "opengl",
    "vulkan",
    "assets",
    "gui"
]
categories = [
    "rendering",
    "rendering::engine",
    "gui",
    "graphics"
]
license-file = "LICENCE"

[features]
vulkan = ["dep:vulkano", "dep:vulkano-win", "dep:vulkano_maybe_molten", "dep:glsl-to-spirv", "dep:raw-window-handle", "dep:ash", "glfw/vulkan"]
gui = ["dep:roxmltree"]
3d = ["dep:gltf"]

[dependencies]
mvutils = { path = "../MVUtils" }
include_dir = "0.7.3"
glfw = "0.51.0"
gl = "0.14.0"
regex = "1.7.3"
glam = "0.24.0"
once_cell = "1.17.1"
bytebuffer = "2.1.1"
json = "0.12.4"
image = "0.24.6"
bitflags = "2.2.1"
openal = "0.2.2"
itertools = "0.10.5"
roxmltree = { version = "0.18.0", optional = true }
gltf = { version = "1.1.0", optional = true }

#vulkan shit that doesn't work

vulkano = { version = "0.33.0", optional = true, features = ["default", "document_unchecked"] }
vulkano-win = { version = "0.33.0", optional = true }
vulkano_maybe_molten = { version = "0.30.1", optional = true }
glsl-to-spirv = { version = "0.1.7", optional = true }
ash = { version = "0.37.2", optional = true }
raw-window-handle = { version = "0.5.2", optional = true }

[target."cfg(target_os = \"macos\")".dependencies.objc]
version = "0.2"

[target."cfg(target_os = \"windows\")".dependencies.winapi]
version = "0.3"
features = ["libloaderapi"]
