[package]
name = "mvcore"
version = "0.1.0"
edition = "2021"
description = "The MV core library. Rendering, assets and GUI."
authors = [
    "Maxim Savenkov <mqxf@mvteam.dev>",
    "Julian Hohenhausen <v22@mvteam.dev>"
]
readme = "README.md"
keywords = [
    "mvcore",
    "rendering",
    "wgpu",
    "assets",
    "gui"
]
categories = [
    "rendering",
    "rendering::engine",
    "gui",
    "graphics"
]
license-file = "LICENCE"

[[test]]
name = "test"
path = "tests/main.rs"
harness = false

[profile.release]
opt-level = 3
strip = true
lto = true
debug = false
debug-assertions = false
codegen-units = 1
panic = "unwind"

[features]
ui = []
3d = ["dep:gltf"]
ray-tracing = ["3d"]
# vr = ["dep:openxr", "3d"]

[dependencies]

# internal dependencies
mvcore-proc-macro = { path = "Proc" }

# mvteam dependencies
mvutils = "0.5.7"
mvsync = "1.1.4"
mvlogger = "0.3.0"

# general dependencies
bytebuffer = "2.2.0"
itertools = "0.12.0"
log = "0.4.20"
num-traits = "0.2.17"
hashbrown = "0.14.3"
bitflags = "2.5.0"
parking_lot = "0.12.1"

# specific dependencies
include_dir = "0.7.3"
shaderc = "0.8.3"
openal = "0.2.2"
image = "0.25.0"

# rendering dependencies
winit = "0.29.15"

# vulkan dependencies
ash = "0.37.3"
gpu-alloc = "0.6.0"
gpu-alloc-ash = "0.6.0"

# to be replaced
# ideally remove, for more lightweight one, or custom math for the limited functionality we need.
glam = "0.27.0"

# 3d dependencies
gltf = { version = "1.4.0", optional = true }

# vr dependencies
# openxr = { version = "0.18.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]

# metal dependencies
metal = "0.27.0"
objc = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]

# directx dependencies
d3d12 = "0.19.0"
winapi = "0.3.9"
